# Generated by Django 5.0.14 on 2026-07-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Carga')),
                ('csv_file', models.FileField(upload_to='csv_uploads/', verbose_name='Archivo CSV')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='pdf_reports/', verbose_name='Reporte Clínico PDF')),
                ('notebook_file', models.FileField(blank=True, null=True, upload_to='notebooks/', verbose_name='Cuaderno Jupyter .ipynb')),
                ('total_records', models.IntegerField(default=0, verbose_name='Registros Totales')),
                ('predicted_dropouts', models.IntegerField(default=0, verbose_name='Desertores Predichos')),
                ('accuracy_estimate', models.FloatField(default=96.36, verbose_name='Estimación de Exactitud (%)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
            ],
            options={
                'verbose_name': 'Carga de CSV Predictiva',
                'verbose_name_plural': 'Cargas de CSV Predictivas',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
